DEFAULT_THREADS = 4
MAX_THREADS = 8
MAX_PAGES_WITHOUT_CONFIRM = 500
MIN_EXTRACTABLE_TEXT_CHARS = 10

TOOL_PDFINFO = "pdfinfo"
TOOL_PDFTOTEXT = "pdftotext"
TOOL_PDF2ZH = "pdf2zh"
TOOL_OCRMYPDF = "ocrmypdf"
TOOL_GHOSTSCRIPT = "gswin64c"

PDF_MAGIC = b"%PDF"
